export type IconName = 
    | 'favorite'
    | 'favorite-outline'
    | 'profile'
    | 'time'
    | 'star'
    | 'location'
    | 'calendar'
    | 'search'
    | 'filter'
    | 'qr-code'
    | 'qr-code2'
    | 'route'
    | 'arrow-left'
    | 'arrow-bottom'
    | 'cross'
    | 'settings'
    | 'abonement'
    | 'bell'
    | 'profile-circle'
    | 'card'
    | 'arrow-right'
    | 'in-map'
    | 'stop'
    | 'megaphone'
    | 'location-flag'
    | 'palm'
    | 'beach'
    | 'check'
    | 'check2'
    | 'check3'
    | 'like';

export type IconSize = 'extra-small' | 'small' | 'medium' | 'large';

export type IconColor = 'secondary';