networks:
  main:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
    external: true

services:
  nginx_shezlongs_front:
    container_name: front_nginx
    build:
      context: ./nginx
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ../:/app
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/ssl/:/etc/nginx/ssl
    networks:
      main:
        ipv4_address: 172.18.0.253