export const Routes = {
  Home: '/',
  Init: '/init',
  Cities: '/cities',
  Auth: '/auth',
  Verification: '/verification',
  Profile: '/profile',
  ProfileEdit: '/profile-edit',
  Locations: '/locations',
  Location: '/location/:id',
  Sector: '/sector/:id',
  Favorites: '/favorites',
  Notifications: '/notifications',
  NotificationSettings: '/notifications-settings',
  Abonements: '/abonements',
  Abonement: '/abonement',
  Booking: '/booking',
  BookingDetails: '/booking/:id',
  BookingDetailsQR: '/booking/:id/qr',
  BookingDetailsReceipt: '/booking/:id/receipt',
  PaymentMethods: '/payment-methods',
  PaymentMethodsAdd: '/payment-methods-add',
  Support: '/support',
  Privacy: 'privacy-policy',
  UiKit: '/ui-kit',
  Filters: '/filters',
  StaffCall: '/staffcall',
} as const;
