export const Routes = {
  Home: '/',
  Init: '/init',
  Cities: '/cities',
  Auth: '/auth',
  Verification: '/verification',
  Profile: '/profile',
  ProfileEdit: '/profile-edit',
  Locations: '/locations',
  Location: '/location/:id',
  Sector: '/sector/:id',
  Module: '/module/:id',
  Favorites: '/favorites',
  Notifications: '/notifications',
  NotificationSettings: '/notifications-settings',
  Abonements: '/abonements',
  Abonement: '/abonement',
  Booking: '/booking',
  PaymentMethods: '/payment-methods',
  Support: '/support',
  Privacy: 'privacy-policy',
  UiKit: '/ui-kit',
  Filters: '/filters',
  Receipt: '/receipt',
  StaffCall: '/staffcall',
} as const;
